---
title: "Case Study 06"
author: Hui Gao
date: October 12, 2021
output: github_document
---

## Load Packages

```{r message=FALSE}
library(raster)
library(sp)
library(spData)
library(tidyverse)
library(sf)
library(knitr)
```

## Load Data

```{r message=FALSE}
data(world)  #load 'world' data from spData package
tmax_monthly <- getData(name = "worldclim", var="tmax", res=10) #load climate data

```

## Maximum Temperature of Each Country

```{r message=FALSE}
world <- world %>%
  filter(!continent=="Antarctica")
world <- as(world, "Spatial")

gain(tmax_monthly) <- .1
tmax_annual <- max(tmax_monthly)
names(tmax_annual) <- "tmax"

tmax_annual_country <- raster::extract(tmax_annual, world, fun=max, na.rm=TRUE, small=TRUE, sp=TRUE) %>%
  st_as_sf()

ggplot() +
  geom_sf(data = tmax_annual_country, aes(fill = tmax)) +
  scale_fill_viridis_c(name="Annual\nMaximum\nTemperature (C)") +
  theme(legend.position = 'bottom')
```

## Hottest Country on Each Continent

```{r message=FALSE, results='asis'}
hottest_continents <- tmax_annual_country %>%
  group_by(continent) %>%
  slice_max(tmax, n = 1) %>%
  select(name_long, continent, tmax) %>%
  arrange(desc(tmax)) %>%
  st_set_geometry(NULL)
kable(hottest_continents)
```
