---
title: "Case Study 10"
author: Hui Gao
date: November 10, 2021
output: github_document
---
 
## Load libraries
```{r message=FALSE}
library(raster)
library(rasterVis)
library(rgdal)
library(ggmap)
library(tidyverse)
library(knitr)
library(ncdf4)
```

## Download data
```{r message=FALSE, warning=FALSE}
# Create a folder to hold the downloaded data
dir.create("data",showWarnings = F)

lulc_url="https://github.com/adammwilson/DataScienceData/blob/master/inst/extdata/appeears/MCD12Q1.051_aid0001.nc?raw=true"
lst_url="https://github.com/adammwilson/DataScienceData/blob/master/inst/extdata/appeears/MOD11A2.006_aid0001.nc?raw=true"

# download them
download.file(lulc_url,destfile="data/MCD12Q1.051_aid0001.nc", mode="wb")
download.file(lst_url,destfile="data/MOD11A2.006_aid0001.nc", mode="wb")

lulc=stack("data/MCD12Q1.051_aid0001.nc",varname="Land_Cover_Type_1")
lst=stack("data/MOD11A2.006_aid0001.nc",varname="LST_Day_1km")
```

## Explore LULC data
```{r message=FALSE}
plot(lulc)
```

```{r message=FALSE}
# Select the 2013 landcover data
lulc=lulc[[13]]
plot(lulc)
```

## Process landcover data
```{r message=FALSE}
Land_Cover_Type_1 = c(
    Water = 0, 
    `Evergreen Needleleaf forest` = 1, 
    `Evergreen Broadleaf forest` = 2,
    `Deciduous Needleleaf forest` = 3, 
    `Deciduous Broadleaf forest` = 4,
    `Mixed forest` = 5, 
    `Closed shrublands` = 6,
    `Open shrublands` = 7,
    `Woody savannas` = 8, 
    Savannas = 9,
    Grasslands = 10,
    `Permanent wetlands` = 11, 
    Croplands = 12,
    `Urban & built-up` = 13,
    `Cropland/Natural vegetation mosaic` = 14, 
    `Snow & ice` = 15,
    `Barren/Sparsely vegetated` = 16, 
    Unclassified = 254,
    NoDataFill = 255)

lcd=data.frame(
  ID=Land_Cover_Type_1,
  landcover=names(Land_Cover_Type_1),
  col=c("#000080","#008000","#00FF00", "#99CC00","#99FF99", "#339966", "#993366", "#FFCC99", "#CCFFCC", "#FFCC00", "#FF9900", "#006699", "#FFFF00", "#FF0000", "#999966", "#FFFFFF", "#808080", "#000000", "#000000"),
  stringsAsFactors = F)
# colors from https://lpdaac.usgs.gov/about/news_archive/modisterra_land_cover_types_yearly_l3_global_005deg_cmg_mod12c1
kable(head(lcd))
```

```{r message=FALSE}
# define as a categorical variable
lulc=as.factor(lulc)

# update the RAT with a left join
levels(lulc)=left_join(levels(lulc)[[1]],lcd)

```

```{r message=FALSE}
# plot it
gplot(lulc)+
  geom_raster(aes(fill=as.factor(value)))+
  scale_fill_manual(values=levels(lulc)[[1]]$col,
                    labels=levels(lulc)[[1]]$landcover,
                    name="Landcover Type")+
  coord_equal()+
  theme(legend.position = "bottom")+
  guides(fill=guide_legend(ncol=5, nrow=3,byrow=TRUE))

```

## Land Surface Temperature
```{r message=FALSE}
plot(lst[[1:12]])
```

## Convert LST to Degrees C
```{r message=FALSE}
offs(lst)=-273.15
plot(lst[[1:10]])
```

## Add Dates to Z (time) dimension
```{r message=FALSE}
names(lst)[1:5]
```

```{r message=FALSE}
tdates=names(lst)%>%
  sub(pattern="X",replacement="")%>%
  as.Date("%Y.%m.%d")

names(lst)=1:nlayers(lst)
lst=setZ(lst,tdates)
```

## Part 1: Extract timeseries for a point
```{r message=FALSE}
lw=SpatialPoints(data.frame(x=-78.791547,y=43.007211))
projection(lw) = "+proj=longlat"
lw = spTransform(lw, crs(lst))
ts = raster::extract(lst, lw, buffer=1000, fun=mean, na.rm=T)
ts = t(ts)
ts_df = data.frame(temperature = ts, date = getZ(lst))

ggplot(ts_df, aes(date, temperature)) +
  geom_point() +
  geom_smooth(n = 200, span = 0.01, color = "blue") +
  labs(x = "Date", y = "Monthly Mean Land Surface Temperature")
```

## Part 2: Summarize weekly data to monthly climatologies
```{r message=FALSE}
tmonth = as.numeric(format(getZ(lst),"%m"))
lst_month = stackApply(lst, tmonth, fun = mean)
names(lst_month)=month.name
gplot(lst_month) + 
  geom_tile(aes(fill = value)) +
  facet_wrap(~variable) +
  scale_fill_gradient(low = 'blue', high = 'orange') +
  coord_equal() +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5))
```

```{r message=FALSE}
cellStats(lst_month,mean) %>% 
  as.data.frame() %>% 
  rename(Mean = ".") %>% 
  kable() 
```

## Part 3: Summarize Land Surface Temperature by Land Cover
```{r message=FALSE}
lulc2 = raster::resample(lulc, lst, method="ngb")
lcds1 = cbind.data.frame(
  values(lst_month),
  ID=values(lulc2[[1]])) %>%
  na.omit() %>%
  gather(key='month',value='value', -ID) %>%
  mutate(ID=as.numeric(ID), month=factor(month,levels=month.name,ordered=T))

lcds_lcd = left_join(lcds1, lcd, by = "ID") %>%
  filter(landcover%in%c("Urban & built-up","Deciduous Broadleaf forest"))

ggplot(lcds_lcd, aes(month, value)) +
  geom_jitter() +
  geom_boxplot() +
  facet_wrap(~landcover) +
  labs(x = "Month", y = "Monthly Mean Land Surface Temperature (C)") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5))
```
