---
title: "Case Study 05"
author: Hui Gao
date: October 5, 2021
output: github_document
---

## Load Packages

```{r message=FALSE}
library(spData)
library(sf)
library(tidyverse)
library(units)
```

## Load Data

```{r message=FALSE}
data(world)
data(us_states)

head(world)
head(us_states)
```

## New York Land Within 10km of Canada

```{r message=FALSE}
# Define projection
albers <- "+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs"

# Filter
canada <- world %>%
  filter(name_long == "Canada")
ny <- us_states %>%
  filter(NAME == "New York")

# Projection transformation
canada <- st_transform(canada, albers)
ny <- st_transform(ny, albers)

# Calculate buffer and intersection
canada <- st_buffer(canada, 10000)
border <- st_intersection(ny, canada)

# Plot
ggplot() +
  geom_sf(data = ny) +
  geom_sf(data = border, fill = "red") +
  ggtitle("New York Land Within 10km of Canada")

# Calculate area
border_area <- st_area(border) %>%
  set_units(km^2)
print(border_area)

```

