---
title: "Case Study 04"
author: Hui Gao
date: September 28, 2021
output: github_document
---

## Farthest Destination Airport

The full name of the destination airport farthest from any of the NYC airports in the flights table.

```{r}
library(tidyverse)
library(nycflights13)


farthest_flights <- flights %>%
  arrange(desc(distance)) %>%
  slice(1)

names(airports)[names(airports) == 'faa'] <- 'dest'

farthest_airport <- farthest_flights %>%
  left_join(airports, by="dest") %>%
  select(name)

farthest_airport <- as.character(farthest_airport)
print(farthest_airport)
```

## Airports Locations

Locations of all airports in the airports table.

```{r}
airports %>%
  distinct(lon,lat) %>%
  ggplot(aes(lon, lat)) +
    borders("world") +
    geom_point(col="red") +
    coord_quickmap()
```

## Mean Delays

Locations of all airports in the airports table.

```{r}
airports_meanDelay <- flights %>%
  group_by(dest) %>%
  summarise(mean_delay=mean(arr_delay, na.rm=TRUE))

airports_MD <- airports_meanDelay %>%
  left_join(airports, by="dest")

ggplot(airports_MD, aes(lon, lat, color=mean_delay)) +
  borders("state") +
  geom_point() +
  coord_quickmap()
```